### ISSUE TITLE
Create a service component for other teams to use

### ISSUE THREAD

**Issue by JCharante** [AustinShalit/CS3733-D19-Team-O-Project#396]
We will be bulking out our support animal request.

- [ ] Ability to "shop" for an animal - you can scroll through a bunch of pictures to pick the service request animal you'd like
- [ ] Specify the time frame you'd like the animal for
- [ ] have information about each animal you can choose from (age, type, name, etc.)
